apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: pangolin

servers: 1
agents: 2

image: rancher/k3s:v1.34.1-k3s1

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
